name: Semgrep SAST Scan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Show Semgrep version
        run: semgrep --version

      - name: Create reports folder
        run: mkdir -p reports/semgrep

      - name: Run Semgrep JSON report
        run: semgrep scan --config "p/default" . --json --output reports/semgrep/semgrep-sast-report.json || true

      - name: Run Semgrep SARIF report
        run: semgrep scan --config "p/default" . --sarif --output reports/semgrep/semgrep-sast-report.sarif || true

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-json-report
          path: reports/semgrep/semgrep-sast-report.json

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif-report
          path: reports/semgrep/semgrep-sast-report.sarif
