name: Semgrep SAST Scan

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Create reports folder
        run: mkdir -p reports/semgrep

      - name: Run Semgrep JSON report
        run: semgrep scan --config "p/default" . --json --output reports/semgrep/semgrep-sast-report.json || true

      - name: Run Semgrep SARIF report
        run: semgrep scan --config "p/default" . --sarif --output reports/semgrep/semgrep-sast-report.sarif || true

      - name: Commit reports to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add reports/semgrep/semgrep-sast-report.json reports/semgrep/semgrep-sast-report.sarif
          git diff --cached --quiet || git commit -m "Add Semgrep SAST reports"
          git push
